camunda.bpm.client:
  base-url: http://localhost:8080/engine-rest
  lock-duration: 10000
  subscriptions:
    ExternalTaskTest:
      variable-names: []
      process-definition-key: ExternalTaskClientExample

logging.level.org.camunda.bpm.client: DEBUG